const $=(s,p=document)=>p.querySelector(s);const $$=(s,p=document)=>[...p.querySelectorAll(s)];
const toast=$('#toast');let timer;
const BACKEND='https://swing-pro-ai26-ai-backend.vercel.app';
function showToast(message){if(!toast)return;toast.textContent=message;toast.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>toast.classList.remove('show'),2600)}
function calculateRisk(){const entry=Number($('#entry')?.value)||0,stop=Number($('#stop')?.value)||0,capital=Number($('#capital')?.value)||0,riskPct=Number($('#riskPct')?.value)||0;const perUnit=Math.abs(entry-stop);const maxLoss=capital*riskPct/100;const qty=perUnit?Math.floor(maxLoss/perUnit):0;if($('#qty'))$('#qty').textContent=qty;if($('#riskText'))$('#riskText').textContent=`Max loss ≈ ₹${Math.round(qty*perUnit).toLocaleString('en-IN')}`}
function nextThursday(){const d=new Date();const day=d.getDay();let add=(4-day+7)%7;if(add===0)add=7;d.setDate(d.getDate()+add);return d.toISOString().slice(0,10)}
function ensureLiveFields(){const grid=$('.risk-panel .form-grid');if(!grid||$('#strike'))return;grid.insertAdjacentHTML('beforeend','<label>Strike<input id="strike" type="number" readonly placeholder="Live"></label><label>Expiry<input id="expiry" type="text" readonly placeholder="Live"></label>');}
function setValue(id,v){const el=$('#'+id);if(el&&v!==undefined&&v!==null&&v!=='')el.value=v}
function optionRows(data){return Array.isArray(data?.data)?data.data:Array.isArray(data)?data:[]}
function getSide(row,type){return type==='PUT'?row.put_options:row.call_options}
function chooseContract(rows,type,targetPremium){let best=null,bestDiff=Infinity;for(const row of rows){const side=getSide(row,type);const ltp=Number(side?.market_data?.ltp);if(!side||!Number.isFinite(ltp)||ltp<=0)continue;const diff=Math.abs(ltp-targetPremium);if(diff<bestDiff){bestDiff=diff;best={row,side,ltp}}}return best}
async function runLiveAnalysis(){ensureLiveFields();const btn=$('#analyzeBtn');if(btn){btn.disabled=true;btn.dataset.old=btn.textContent;btn.textContent='Loading live option chain…'}showToast('Connecting to live Upstox option chain…');try{const type=$('#optionType')?.value||'CALL';const targetPremium=Number($('#entry')?.value)||100;const expiry=nextThursday();const url=`${BACKEND}/api/options?instrument_key=${encodeURIComponent('NSE_INDEX|Nifty 50')}&expiry_date=${encodeURIComponent(expiry)}`;const response=await fetch(url,{headers:{Accept:'application/json'}});const data=await response.json();if(!response.ok)throw new Error(data?.error||`API error ${response.status}`);const rows=optionRows(data);const selected=chooseContract(rows,type,targetPremium);if(!selected)throw new Error('No valid option contracts returned. Check the Upstox token or expiry.');const strike=Number(selected.row.strike_price);const ltp=selected.ltp;setValue('strike',strike);setValue('expiry',selected.row.expiry||expiry);setValue('entry',Number(ltp.toFixed(2)));setValue('stop',Number((ltp*0.95).toFixed(2)));setValue('target1',Number((ltp*1.10).toFixed(2)));setValue('target2',Number((ltp*1.15).toFixed(2)));setValue('target3',Number((ltp*1.20).toFixed(2)));calculateRisk();const contract=selected.side?.instrument_key||'';const label=type==='PUT'?'PUT':'CALL';if($('#marketState'))$('#marketState').textContent='Live option chain';showToast(`${label} ${strike} live premium ₹${ltp.toFixed(2)} loaded.`);if(contract&&$('#journalSymbol')&&!$('#journalSymbol').value)$('#journalSymbol').value=`NIFTY ${strike}`;}catch(error){console.error(error);showToast(`Live analysis failed: ${error.message}`)}finally{if(btn){btn.disabled=false;btn.textContent=btn.dataset.old||'Run AI analysis →'}}}
['entry','stop','target1','target2','target3','capital','riskPct'].forEach(id=>$('#'+id)?.addEventListener('input',calculateRisk));
ensureLiveFields();calculateRisk();
$('#analyzeBtn')?.addEventListener('click',runLiveAnalysis);
$('#optionType')?.addEventListener('change',()=>showToast('Option side changed. Run analysis for a live contract.'));
$('#refreshBtn')?.addEventListener('click',()=>{showToast('Market snapshot refreshed.');if($('#marketState'))$('#marketState').textContent='Updated just now'});
$('#scanBtn')?.addEventListener('click',()=>showToast('Scanner found 2 bullish setups and 1 WAIT setup.'));
$('#alertsBtn')?.addEventListener('click',()=>showToast('No new alerts.'));
$('#uploadBtn')?.addEventListener('click',()=>$('#chartInput')?.click());
$('#chartInput')?.addEventListener('change',e=>{if(e.target.files?.[0])showToast('Chart received. AI scanner is ready for analysis.');});
$$('.stock-row').forEach(row=>row.addEventListener('click',()=>{if(row.dataset.symbol)showToast(`${row.dataset.symbol}: setup details opened.`)}));

const shareBtn=$('#shareBtn');
if(shareBtn){shareBtn.addEventListener('click',()=>{const type=$('#optionType')?.value||'CALL';const strike=$('#strike')?.value||'';const expiry=$('#expiry')?.value||'';const entry=$('#entry')?.value||'';const stop=$('#stop')?.value||'';const t1=$('#target1')?.value||'';const t2=$('#target2')?.value||'';const t3=$('#target3')?.value||'';if(!entry||!stop||!t1){showToast('Run live analysis first.');return}const text=`🎯 ${type} OPTION SETUP\n\nStrike: ${strike}\nEntry: ₹${entry}\nStop Loss: ₹${stop}\nTarget 1: ₹${t1}\nTarget 2: ₹${t2}\nTarget 3: ₹${t3}\n${expiry?`Expiry: ${expiry}\n`:''}\n💡 Tips:\n• Enter only after confirmation.\n• Keep Stop Loss fixed.\n• Book partial profit at targets.\n• Follow your risk limit.\n• Avoid overtrading.\n\n⚠️ Educational/decision support only.`;window.location.assign(`https://api.whatsapp.com/send?text=${encodeURIComponent(text)}`);});}

const JOURNAL_KEY='swingProAI_trading_journal_v1';
function getJournal(){try{return JSON.parse(localStorage.getItem(JOURNAL_KEY)||'[]')}catch{return[]}}
function setJournal(rows){localStorage.setItem(JOURNAL_KEY,JSON.stringify(rows))}
function renderJournal(){const box=$('#journalList');if(!box)return;const rows=getJournal();if(!rows.length){box.innerHTML='<div class="metric"><span>No saved trades yet</span><small>Save a trade and it will appear here.</small></div>';return}box.innerHTML=rows.slice().reverse().map(r=>`<div class="stock-row"><div><b>${escapeHtml(r.date)} · ${escapeHtml(r.symbol||'-')}</b><small>${escapeHtml(r.option)} · Entry ₹${escapeHtml(r.entry)} → Exit ₹${escapeHtml(r.exit)} · Qty ${escapeHtml(r.qty)}</small></div><strong class="${Number(r.pnl)>=0?'green':'wait'}">₹${Number(r.pnl||0).toLocaleString('en-IN')}</strong></div>`).join('')}
function escapeHtml(v){return String(v??'').replace(/[&<>'\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','\"':'&quot;'}[c]))}
$('#saveJournalBtn')?.addEventListener('click',()=>{const row={date:$('#journalDate')?.value||new Date().toISOString().slice(0,10),symbol:$('#journalSymbol')?.value.trim()||'N/A',option:$('#journalOption')?.value||'CALL',entry:$('#journalEntry')?.value||'',exit:$('#journalExit')?.value||'',qty:$('#journalQty')?.value||'',pnl:$('#journalPnl')?.value||'0',notes:$('#journalNotes')?.value.trim()||''};if(!row.entry||!row.exit||!row.qty){showToast('Entry, Exit and Quantity are required.');return}const rows=getJournal();rows.push(row);setJournal(rows);renderJournal();['journalSymbol','journalEntry','journalExit','journalQty','journalPnl','journalNotes'].forEach(id=>{if($('#'+id))$('#'+id).value=''});showToast('Trade saved to journal.');});
function exportJournal(){const rows=getJournal();if(!rows.length){showToast('No journal trades to export.');return}const header=['Date','Symbol','Option','Entry Premium','Exit Premium','Quantity','P&L (₹)','Notes'];const body=rows.map(r=>[r.date,r.symbol,r.option,r.entry,r.exit,r.qty,r.pnl,r.notes]);const esc=v=>`<td>${escapeHtml(v)}</td>`;const table=`<html><head><meta charset="UTF-8"></head><body><table border="1"><tr>${header.map(h=>`<th>${escapeHtml(h)}</th>`).join('')}</tr>${body.map(r=>`<tr>${r.map(esc).join('')}</tr>`).join('')}</table></body></html>`;const blob=new Blob([table],{type:'application/vnd.ms-excel'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`Swing-Pro-AI-Trading-Journal-${new Date().toISOString().slice(0,10)}.xls`;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);showToast('Excel journal downloaded.');}
$('#exportJournalBtn')?.addEventListener('click',exportJournal);renderJournal();
$$('.nav-item').forEach(btn=>btn.addEventListener('click',()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));btn.classList.add('active');const tab=btn.dataset.tab;if(tab==='scanner'){$('#uploadBtn')?.scrollIntoView({behavior:'smooth',block:'center'});showToast('AI Chart Scanner ready.')}else if(tab==='market'){$('.signal-panel')?.scrollIntoView({behavior:'smooth',block:'center'});showToast('Market dashboard selected.')}else if(tab==='watchlist'){$('#stockList')?.scrollIntoView({behavior:'smooth',block:'center'});showToast('Watchlist selected.')}else if(tab==='settings')$('.disclaimer')?.scrollIntoView({behavior:'smooth',block:'center'});else window.scrollTo({top:0,behavior:'smooth'})}));
window.addEventListener('load',()=>showToast('Swing Pro AI terminal loaded.'));